server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /healthz {
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location = / {
        return 302 /cnp/;
    }

    location = /cnp {
        return 301 /cnp/;
    }

    location /cnp/ {
        try_files $uri $uri/ /cnp/index.html;
    }
}

